title: Magic Eight Ball
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: A Random Magic 8 Ball
  - title: Adding Sentiment Analysis
  - title: Designing the User Interface
  - title: "Challenge: Change the responses"
    challenge: true