---
title: Sentimental 8-ball
hero_image: images/banner.png
description:
version: 4
listed: true
copyedit: true
last_tested: '2018-12-06'
steps:
- title: Introduction
  completion: engaged
- title: Make a Magic 8 Ball which gives answers at random
- title: Add sentiment analysis
  completion: internal
- title: Design the user interface
- title: 'Challenge: Change the responses'
  challenge: true
